### ISSUE TITLE
Image Search

### ISSUE THREAD

**Issue by davidmw** [danielktaylor/fabric-js-editor#9]
This editor has a nice simple UI and could be very useful in my project.

Running on OSX with Safari 11.x - the Image Search browser works and displays a grid of images. However when a clipart is selected it does not appear on the canvas.

Is the developer (or any watcher) available to discuss updating / extending the project for us on a freelance basis?  If so please provide contact details.

**Comment by danielktaylor** [comment]
Hi @davidmw - it does look like there have been some regressions around the image search. Probably some changes in the openclipart.org API. I imagine quick to fix. The project could also probably use an update to the newest version of Fabric.js, which would be a bit of work because I had to put in a number of workaround for Fabric.js 1.x bugs.

Unfortunately, I don't currently have time to do any freelance work on this project at this time, due to other commitments. I will be able to review and accept any PRs to the project.

**Comment by davidmw** [comment]
Thanks Daniel - closing this as I'll be integrating another editor.
